services:
  transcribe:
    build:
      context: ./
      dockerfile: ./thought-miner-transcribe/Dockerfile
    ports:
    # hostport:container
      - "8000:8000"
    # big W: https://stackoverflow.com/a/76030067
    network_mode: "host"
    # could use interpolation: https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/#:~:text=env%20file-,An%20.,manage%20configuration%20in%20one%20place.
    # for variable volume selection based on prod vs dev
    volumes:
      - /home/arelius/thought-miner:/opt/app/dev
    # environment:
    #   - PYTHONPATH=/opt/app
    command: ["thought-miner-transcribe", "start-server"]
    restart: unless-stopped
    develop:
      # Create a `watch` configuration to update the appl
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync+restart
          path: ./thought-miner-transcribe
          target: /opt/app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./thought-miner-transcribe/pyproject.toml

  alignment:
    build:
      context: ./
      dockerfile: ./thought-miner-alignment/Dockerfile
    ports:
      - "8001:8001"
    network_mode: "host"
    volumes:
      - /home/arelius/thought-miner:/opt/app/dev
    environment:
      - PYTHONPATH=/opt/app
    command: ["thought-miner-alignment", "start-server"]
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./thought-miner-alignment
          target: /opt/app
          ignore:
            - .venv/
        - action: rebuild
          path: ./thought-miner-alignment/pyproject.toml

  nextjs:
    build:
      context: ./thought-miner-webui
      dockerfile: Dockerfile
    container_name: thought-miner-nextjs
    ports:
      - '3000:3000'
    volumes:
      - ./thought-miner-webui:/app
      # - /app/node_modules
      - /app/.next
      - /home/arelius/thought-miner:/opt/app/dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@postgres:5432/thoughtminer
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./thought-miner-webui
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./thought-miner-webui/package.json

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thoughtminer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d thoughtminer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: